### ISSUE TITLE
Add support for replicateSubscriptionState to Consumers

### ISSUE THREAD

**Issue by david-streamlio** [david-streamlio/pulsar-nifi-bundle#45]
[replicateSubscriptionState](https://pulsar.apache.org/api/client/2.9.0-SNAPSHOT/org/apache/pulsar/client/api/ConsumerBuilder.html#replicateSubscriptionState-boolean-)

**Comment by nathluu** [comment]
I created pull request #49 for this issue. Please help to review it.
